#!/usr/bin/env php
<?php

declare(strict_types=1);

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

require dirname(__DIR__, 3).'/vendor/autoload.php';

/** @var Application $app */
$app = require __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput());

exit($status);
